[package]
name = "rust-poc"
version = "0.1.0"
authors = ["not-avail <not-avail@not-avail>"]

[dependencies]
librustpad = { path = "../librustpad" }
image = "*"
evdev = "*"
epoll = "3.1.1"
libc = "*"
chrono = "*"