[package]
name = "rustspy"
version = "0.1.0"
authors = ["not-avail <not-avail@not-avail>"]

[lib]
name = "rustspy"
crate_type = ["dylib"]

[dependencies]
redhook = "0.1.1"
nix = "0.10.0"
libc = "0.2.37"
enumflags = "0.3.0"
enumflags_derive = "0.3.0"
