[package]
name = "librustpad"
version = "0.1.0"
authors = ["not-avail <not-avail@not-avail>"]

[dependencies]
ioctl-gen = "0.1.0"
libc = "0.2.37"
mmap = "0.1.1"
rusttype = "0.4.1"
evdev = "*"
epoll = "3.1.1"
image = "*"
rb = "0.3.1"
line_drawing = "0.7.0"
hlua = "*"